name: Deploy bookhub-backend
on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Source
              uses: actions/checkout@v4
            # - name: Login to Docker Hub
            #   uses: docker/login-action@v2
            #   with:
            #       username: ${{ secrets.DOCKERHUB_USERNAME }}
            #       password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Login to docker hub
              run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            - name: Build Docker Image
              run: docker build -t ella0110/bookhub_backend  .
            - name: Publish Image to docker hub
              run: docker push ella0110/bookhub_backend:latest

    deploy:
        needs: build
        runs-on: self-hosted
        steps:
            - name: Pull image from docker hub
              run: docker pull ella0110/bookhub_backend:latest
            - name: Delete old container
              run: docker rm -f bookhub-backend-container
            - name: Run Docker Container
              run: docker run -d -p 5555:5555 --name bookhub-backend-container -e MONGO_PASSWORD='${{ secrets.MONGO_PASSWORD }}' ella0110/bookhub_backend
