name: Deploy bookhub-backend
on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Source
              uses: actions/checkout@v4
            # - name: Login to Docker Hub
            #   uses: docker/login-action@v2
            #   with:
            #       username: ${{ secrets.DOCKERHUB_USERNAME }}
            #       password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Login to docker hub
              run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            - name: Build Docker Image
              run: docker build -t ella0110/bookhub_backend  .
            - name: Publish Image to docker hub
              run: docker push ella0110/bookhub_backend:latest

    deploy:
        needs: build
        runs-on: self-hosted
        steps:
            - name: Pull image from docker hub
              run: sudo docker pull ella0110/bookhub_backend:latest
            - name: Delete old container
              run: sudo docker rm -f bookhub-backend-container
            - name: Generate .env file
              run: |
                  cat <<EOF > .env
                  CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}
                  DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
                  JWT_COOKIE_EXPIRES_IN=${{ secrets.JWT_COOKIE_EXPIRES_IN }}
                  JWT_EXPIRES_IN=${{ secrets.JWT_EXPIRES_IN }}
                  JWT_SECRET=${{ secrets.JWT_SECRET }}
                  MONGO_CONNECTION_STRING=${{ secrets.MONGO_CONNECTION_STRING }}
                  NODE_ENV=${{ secrets.NODE_ENV }}
                  PUBLIC_CLOUDINARY_API_KEY=${{ secrets.PUBLIC_CLOUDINARY_API_KEY }}
                  PUBLIC_CLOUDINARY_CLOUD_NAME=${{ secrets.PUBLIC_CLOUDINARY_CLOUD_NAME }}
                  STRIPE_API_KEY=${{ secrets.STRIPE_API_KEY }}
                  EOF
            - name: Run Docker Container
              run: sudo docker run -d -p 5555:5555 --name bookhub-backend-container --env-file .env ella0110/bookhub_backend
